### ISSUE TITLE
"Looks like we got no XML document"

### ISSUE THREAD

**Issue by DavidBuell** [thybag/PHP-SharePoint-Lists-API#83] opened 2015-10-30 23:30 UTC
I had successfully implemented your API and have been using it for months. Then yesterday morning it had mysteriously stopped working. I checked the response in my Network tab and it says

"Looks like we got no XML document"

I don't believe I changed anything. I began debugging and dumped the response form the Authentication in the SharePointOnlineAuth.php __doRequest function. It displayed:

"403 Forbidden".

Is the "403 Forbidden" valid and they're now rejecting my authentication request?

I checked all the parameters being passed to the __doRequest function and $location was incorrect. I have the WSDL file URL as:

"https://mysharepointsite............/Lists.asmx?WSDL"

Which displays the XML correctly when going directly to the URL. But when I output $location it is missing the "?WSDL" query string. If I manually append it inside the function, the dump of $response contains the XML from the WSDL file. If I remove the dump the error in my Network tab now says "Error (VersionMismatch) Wrong Version".

I've tried setting SOAP version to SOAP_1_2 but no luck there.

Should the $location variable contain the querystring?

I'm using the "SPONLINE" authentication mode. Can you confirm the API still works for this and that Microsoft didn't break your code by changing something on their end in the last 2 days?

Please help.

**Comment by DavidBuell** [comment] 2015-10-31 00:00
The configureAuthCookies function also seems to have the "?WSDL" query string missing from the $location variable but returns the token and sets authentication cookie successfully, so I'm guessing that's not the issue.

When I dump the $action variable in the __doRequest it's set to:

"http://schemas.microsoft.com/sharepoint/soap/GetList"

Could it be authenticating me but denying the query for some reason? This stuff is all a little over my head, just trying to do the best I can.

**Comment by mgroat** [comment] 2015-11-02 14:13
I think it might be something that was changed by Microsoft. I'm getting the same error, and like you I'm on Sharepoint Online and haven't made any changes to my code recently.

Below is the stacktrace I'm getting:
`
exception 'Exception' with message 'Error (Client) looks like we got no XML document,more=' in C:\webserverpath\sharepointAPI\src\Thybag\SharePointAPI.php:1013
Stack trace:
#0 C:\webserverpath\sharepointAPI\src\Thybag\SharePointAPI.php(444): Thybag\SharePointAPI->onError(Object(SoapFault))
#1 C:\webserverpath\sharepointAPI\src\Thybag\Service\QueryObjectService.php(192): Thybag\SharePointAPI->read('listname', NULL, Object(Thybag\Service\QueryObjectService), NULL)
#2 C:\webserverpath\PickList.php(83): Thybag\Service\QueryObjectService->get()
#3 {main}
`

**Comment by cetonline** [comment] 2015-11-02 16:09
Same thing happened to me.  I haven't made any changes and am also getting the same errors.  Started over the weekend.
I get a nearly identical stactrace error message as mgroat.
When I add in a print_r($this->__getLastResponse()) at line 444 on src\Thybag\SharpointAPI.php
I get "403 FORBIDDEN"

**Comment by DavidBuell** [comment] 2015-11-02 19:56
The first place I can track down the issue is in the configureAuthCookies function in the SharePointOnlineAuth.php file. This line:

######// Create XML security token request
		$xml = $this->generateSecurityToken($login, $password, $endpoint);

returns the token with the message:

######{"error":{"type":"Exception","message":"Error (Sender) looks like we got no XML document,more=","file":"C:\\inetpub\\wwwroot\\laravel-beyer\\vendor\\thybag\\php-sharepoint-lists-api\\src\\Thybag\\SharePointAPI.php","line":983}}

at the end, after the token. I have been in communication with Microsoft and the rep was very nice. I've given him a Fiddle capture and he's also going to elevate the call and is supposed to be looking at this API code to see if they can make it work on their end. I'll post any useful response.

**Comment by DavidBuell** [comment] 2015-11-02 21:20
In the meantime they did link me to this article:

http://paulryan.com.au/2014/spo-remote-authentication-rest/


It mentions getting the request digest which I don't see anywhere in the API. However, this was working without it, maybe that's changed and API needs to be updated to handle this part?

**Comment by DavidBuell** [comment] 2015-11-02 21:49
enabled the CURLOPT_VERBOSE and CURLOPT_HEADER options labled // Useful for debugging and got a more detailed error:

X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.
X-AspNet-Version: 4.0.30319

There was more but that seems to be the important bit. Tried googling the error and it takes me to articles talking about Sharepoint mapped drive configuration. Not sure if that's related.

**Comment by cetonline** [comment] 2015-11-03 15:34
I found it!
So it looks like Microsoft is now sending the authentication Cookies in a different order.
Here is the short fix then I'll explain:
in SharePointOnlineAuth.php
edit the protected function extractAuthCookies on line 143 from 
unset($authCookies[0]); // No need for first cookie
to 
unset($authCookies[2]); // No need for last cookie

The explanation is that we need two specific cookies, the rtFa= and FedAuth= cookies.  But apparently rtFa is now being sent as the first cookie, not the last cookie (there are three cookie headers).  Seems like Microsoft changed the order of the cookie headers.

**Comment by mgroat** [comment] 2015-11-03 16:30
I tested it with that line completely removed and it seemed to work. Created a pull request.

**Comment by DavidBuell** [comment] 2015-11-03 17:38
Awesome! Thanks for your help. I removed the line as well, we may not need the cookie but it's better to have it than break with future changes.

**Comment by cetonline** [comment] 2015-11-03 18:06
Confirmed...removing that line seems like a good move.

**Comment by iharrisempire** [comment] 2015-11-18 23:30
+1 from me.  I made the 'no need for last cookie' change.  Many thanks to whom ever figured this out first!!
If only MS had some sort of change notification/patch notes we could check against!

**Comment by thybag** [comment] 2015-11-25 18:38
Glad to hear @mgroat 's fix is working.

I've not got access to a copy of SharePointOnline, so am pretty reliant other folks reporting & fixing these kinda issues :) The change should now be merged in develop :)

**Closed** 2015-11-25 18:38 UTC

**Comment by hi2u** [comment] 2015-12-03 14:03
I'm having a strange issue where I see the **"Error (Client) looks like we got no XML document,more="** error on some SharePoint Online sub-sites (and the main root site), but not other sub-sites that were set up exactly the same way (I'm just using SharePoint Online defaults everywhere).

I'm using the latest version of SharePointOnlineAuth.php (doesn't contain "unset" anywhere).

I only get the error when doing a recursive query though...

Example that works: 

```php
$sp = new \Thybag\SharePointAPI('username@myorganization.com', 'password', 'http://myorganization.sharepoint.com/sites/MySubSiteOne/_vti_bin/Lists.asmx?wsdl', 'SPONLINE');

$list = $sp->read('Documents'); // this works

$list = $sp->read('Documents',
            NULL,//$limit
            NULL,//$query
            NULL,//$view
            NULL,//$sort
            '<ViewAttributes Scope="RecursiveAll"/>'//$options
        ); // this works
```        

This doesn't work (the only difference is the sub-site I'm connecting to, "MySubSiteTwo"):

```php
$sp = new \Thybag\SharePointAPI('username@myorganization.com', 'password', 'http://myorganization.sharepoint.com/sites/MySubSiteTwo/_vti_bin/Lists.asmx?wsdl', 'SPONLINE');

$list = $sp->read('Documents'); // this works

$list = $sp->read('Documents',
            NULL,//$limit
            NULL,//$query
            NULL,//$view
            NULL,//$sort
            '<ViewAttributes Scope="RecursiveAll"/>'//$options
        ); // this doesn't work, displays: Error (Client) looks like we got no XML document,more=
```        

I did a quick hack on __doRequest() to save the response and headers to a file so I could check that I was getting the XML response containing all the data (yes I am), and also compare the difference in the XML response between the sub-sites that work and don't work.  

Both the working and not-working responses pretty much look the same (they contain a big list of all their files in XML format).  So it looks like the CURL query is getting the XML data back from Microsoft's servers successfully, but the XML parser is breaking, or something like that?

It doesn't seem to be a "response is too big" issue, as it works on my sub-site with the most files, but not on some that only have a few files.  Maybe it's something to do with some sub-sites having characters in filenames that it doesn't like?  But as far as I know there's no weird characters in any of them.  Hard to figure out.

Any ideas?
